# Generated by Django 5.1.2 on 2024-11-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(null=True),
        ),
    ]
